server:
  port: 9001

spring:
  application:
    name: dipo
  thymeleaf:
    prefix: classpath:/templates/
  datasource:
    url: jdbc:mysql://106.55.23.102:3306/chenst?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
#    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: Qq1131460769@
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

eureka:
  instance:
    instance-id: dipo-id
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka

