server:
  port: 9001
#  error:
#    path: /

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  application:
    name: dipo
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  datasource:
    url: jdbc:mysql://106.55.23.102:3306/chenst?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: Qq1131460769@
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

#eureka:
#  instance:
#    instance-id: dipo-id
#    prefer-ip-address: true
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:7001/eureka

