server:
  port: 9001

spring:
  application:
    name: dipo
  thymeleaf:
    prefix: classpath:/templates/

eureka:
  instance:
    instance-id: dipo-id
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
