server:
  port: 9001
#  error:
#    path: /

spring:
  redis:
    database: 1
    host: localhost
    port: 6379
    password:
  application:
    name: dipo
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  datasource:
    url: jdbc:mysql://localhost:3306/chenst?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

#eureka:
#  instance:
#    instance-id: dipo-id
#    prefer-ip-address: true
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:7001/eureka

